<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>RimeAutomation</AssemblyName>
    <RootNamespace>RimeAutomation</RootNamespace>
    <Version>0.1.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
